version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: shelfspace-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: shelfspace

  minio:
    image: minio/minio:latest
    container_name: shelfspace-minio
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # Admin UI
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data

volumes:
  mongo_data:
  minio_data:
